mis1946/autoapp

src/org/rmj/auto/app/views/CustomerForm.fxml
src/org/rmj/auto/app/views/CustomerFormController.java
src/org/rmj/auto/app/views/InputTextFormatter.java
src/org/rmj/auto/app/views/TableClientAddress.java
src/org/rmj/auto/app/views/TableClientEmail.java
src/org/rmj/auto/app/views/TableClientMobile.java
src/org/rmj/auto/app/views/TableClientSocialMedia.java

Debugged saving for Client Master Table setting of BirthDate.
Created new class for client address table details.
Created new class for client mobile table details.
Created new class for client email table details.
Created new class for client social media table details.
Called Table class for populating table views in Customer Form.
Debugged setting of town, zippcode and brgy.
Added loadAddress_txtField for loading and setting textfields values
Added Update Button for Contact Information.
Debugged getItemCount and storing of data in cachedrowset.
Added Validation before inserting address to table.
Added Validation on changing client type.
Debugged remove address.
Debugged Add, Update, remove address and added validation before inserting.
Called Client Mobile class and added in add, edit, …

Autoapp GUI customer info and home

---

src/org/rmj/auto/app/views/FXMLDocument.fxml
src/org/rmj/auto/app/views/FXMLDocumentController.java
src/org/rmj/auto/app/views/TableVehicleDescriptionList.java
src/org/rmj/auto/app/views/VehicleDescriptionForm.fxml
src/org/rmj/auto/app/views/VehicleDescriptionFormController.java

- Created GUI for Vehicle Description Entry.
- Added functionality on controller.
- Call VehicleDescriptionForm.fxml and its controller for loading tab form at menu vehicle description.
- Call InquiryForm.fxml and its controller for loading tab form at menu Inquiry.
- Added Vehicle Description and Inquiry in menu.
- Changed datatype of getMaster of Year, Transmission and Vehicle Size at loadVehicleDescription().
- Debugged Add, Edit and Saving Script.
- Added limit character length and textformatter for year model.
- Adjust size of txtfield02 grid.

Autoapp GUI Vehicle Description

---

src/org/rmj/auto/app/sales/InquiryForm.fxml
src/org/rmj/auto/app/sales/InquiryFormController.java

Created GUI for Inquiry Sales.

Autoapp  GUI  sales inquiry

---

src/org/rmj/auto/app/views/TableVehicleDescriptionList.java
src/org/rmj/auto/app/views/VehicleDescriptionForm.fxml
src/org/rmj/auto/app/views/VehicleDescriptionFormController.java

- Removed browse button since vehicle description list is already displayed.
- Removed / commented unused script.
- Tested Vehicle Description Entry: Error found on editing at saving of concated vehicle description when changing some fields value. - Populating of Vehicle description list is not yet working due to base class is not yet finish.
- Added indexes for storing of data to populate fields.
- Added script for populating table and functionality of search.
- Added pagination.
- Added fix minimum width for table description list to prevent resizing of pagination where clicking next page.

Autoapp GUI  Vehicle Description

---

src/org/rmj/auto/app/sales/SalesAgentForm.fxml
src/org/rmj/auto/app/sales/SalesAgentFormController.java
src/org/rmj/auto/app/views/FXMLDocument.fxml
src/org/rmj/auto/app/views/FXMLDocumentController.java

- Created GUI for Sales Agent Information entry.
- Added menu item for Sales Agent Information Entry.
- Added functionality for menu item Sales Agent to open new tab for sales agent information entry.

Autoapp GUI  Sales Agent Information

---

src/org/rmj/auto/app/sales/TableUnitReceivingDetail.java
src/org/rmj/auto/app/sales/TableUnitReceivingList.java
src/org/rmj/auto/app/sales/UnitReceivingForm.fxml
src/org/rmj/auto/app/sales/UnitReceivingFormController.java
src/org/rmj/auto/app/views/FXMLDocument.fxml
src/org/rmj/auto/app/views/FXMLDocumentController.java

3/29/2023 | Created GUI for Unit Receiving entry.
3/30/2023 | Finalize designing of Unit Receiving Form.
3/30/2023 | Added Minor script to load form.
3/30/2023 | Created class for handling table value for Unit Receiving List.
3/30/2023 | Created class for handling table value for Unit Receiving Details.
3/30/2023 | Added script for populating table and functionality of search.
3/31/2023 | Added script for populating Unit Receiving Detail table and construct script for editable column.
4/1/2023 | Added date FROM and TO for limiting retrieval of data.
4/1/2023 | Added date FROM and TO for limiting retrieval of data.
4/1/2023 | Finalize design.

Autoapp GUI  sales unit receiving

---

src/org/rmj/auto/app/sales/FollowUpDialogForm.fxml
src/org/rmj/auto/app/sales/InquiryForm.fxml
src/org/rmj/auto/app/sales/InquiryFormController.java
src/org/rmj/auto/app/sales/LostOfSalesDialogForm.fxml
src/org/rmj/auto/app/sales/SIBApplicationDialogForm.fxml
src/org/rmj/auto/app/sales/VSAdvancesDialogForm.fxml

INQUIRY SALES GUI WITH DIALOGS GUI

Inquiry Sales GUI with dialogs GUI

---

src/org/rmj/auto/app/views/BankEntryForm.fxml
src/org/rmj/auto/app/views/BankEntryFormController.java

Autoapp Bank  Entry  GUI

---

src/org/rmj/auto/app/sales/TableVehicleEntryList.java
src/org/rmj/auto/app/sales/VehicleEntryForm.fxml
src/org/rmj/auto/app/sales/VehicleEntryFormController.java
src/org/rmj/auto/app/views/FXMLDocument.fxml
src/org/rmj/auto/app/views/FXMLDocumentController.java

- Created new Table model for Vehicle Entry List.
- Added Minor script to load form: To call class only if available.
- Added standard size for tab header, adjust tab title font size to 11 and tab drag and drop feature at TABPANE of HOME.

Autoapp GUI  sales vehicle entry

---

src/org/rmj/auto/app/sales/UnitReceivingFormController.java
src/org/rmj/auto/app/sales/UnitReceivingTableDetail.java
src/org/rmj/auto/app/sales/UnitReceivingTableList.java
src/org/rmj/auto/app/sales/VehicleEntryFormController.java
src/org/rmj/auto/app/sales/VehicleEntryTableList.java
src/org/rmj/auto/app/views/CustomerFormController.java
src/org/rmj/auto/app/views/CustomerTableAddress.java
src/org/rmj/auto/app/views/CustomerTableEmail.java
src/org/rmj/auto/app/views/CustomerTableMobile.java
src/org/rmj/auto/app/views/CustomerTableSocialMedia.java
src/org/rmj/auto/app/views/VehicleDescriptionFormController.java
src/org/rmj/auto/app/views/VehicleDescriptionTableList.java

- Customer
- Vehicle Description
- Vehicle Entry
- Unit Receiving

Refactored the table class name

---

src/org/rmj/auto/app/sales/VehicleEntryTableList.java
src/org/rmj/auto/app/sales/VehicleSalesApproval.fxml
src/org/rmj/auto/app/sales/VehicleSalesApprovalController.java
src/org/rmj/auto/app/sales/VehicleSalesApprovalTable.java

Done adding all functionality, this interface can now approve data, filter, and also select all items to approve.

AutoApp Vehicle Sales Advances for Approval GUI & Controller

---

src/org/rmj/auto/app/sales/ReservationPrint.fxml
src/org/rmj/auto/app/sales/ReservationPrintController.java

This reservation GUI and controller are now working.

Added the reservation print GUI and controller in the customer inquiry process.

---

src/org/rmj/auto/app/bank/BankEntryForm.fxml
src/org/rmj/auto/app/bank/BankEntryFormController.java
src/org/rmj/auto/app/sales/VehicleSalesApprovalController.java
src/org/rmj/auto/app/views/ActivityForm.fxml
src/org/rmj/auto/app/views/ActivityFormController.java
src/org/rmj/auto/app/views/ActivityMemberEntryDialog.fxml
src/org/rmj/auto/app/views/ActivityMemberEntryDialogController.java
src/org/rmj/auto/app/views/ActivityVehicleEntryDialog.fxml
src/org/rmj/auto/app/views/ActivityVehicleEntryDialogController.java
src/org/rmj/auto/app/views/TownCityMainEntryDialog.fxml
src/org/rmj/auto/app/views/TownCityMainEntryDialogController.java

- Redesign Activity Form GUI
- Added Activity Members Form Dialog
- Added Activity Vehicle Entry Dialog 
- Added Town City Main Entry Dialog

AutoApp Re-design Activity Form GUI with three form dialogs

---

src/org/rmj/auto/app/css/FrameStyle.css
src/org/rmj/auto/app/sales/InquiryBankApplicationForm.fxml
src/org/rmj/auto/app/sales/InquiryBankApplicationFormController.java
src/org/rmj/auto/app/sales/InquiryFollowUpForm.fxml
src/org/rmj/auto/app/sales/InquiryFollowUpFormController.java
src/org/rmj/auto/app/sales/InquiryForm.fxml
src/org/rmj/auto/app/sales/InquiryFormController.java
src/org/rmj/auto/app/sales/InquiryLostSaleForm.fxml
src/org/rmj/auto/app/sales/InquiryLostSaleFormController.java
src/org/rmj/auto/app/sales/InquiryVehicleSalesAdvancesForm.fxml
src/org/rmj/auto/app/sales/InquiryVehicleSalesAdvancesFormController.java
src/org/rmj/auto/app/views/CancelForm.fxml
src/org/rmj/auto/app/views/CancelForm.java
src/org/rmj/auto/app/views/CancelFormController.java

- Added Validation on selection of the Inquiry Requirements.
- Added minor script for lost sales controller.
- Removed calling other controller class from the catch logger.
- Mandatory Caps Lock All Columns except Email and Account.
- Changed displaying of client address from textfield to text area and added validation on cancel button.
- Testing field and resize field.
- Added functionality on controller.
- Added loadLostSaleWindow for lost sale tagging.
- Added text formatter that Accepts alpha-numeric characters only for remarks.
- Created cancellation remarks GUI.
- Created Class to be dynamic calling cancellation form.
- Call CancelForm Class at cancelation of Vehicle Sales Advances.
- Call cancellation master class and testing cancellation remarks.
- Added sSourceCD "VSA" from …

Update Inquiry, Lost Sale, Bank Application, Follow-Up , Vehicle Sales Advances and Create Generic Cancellation Remarks

---

src/org/rmj/auto/app/views/VehicleColorFormController.java
src/org/rmj/auto/app/views/VehicleDescriptionFormController.java
src/org/rmj/auto/app/views/VehicleEngineFrameFormatForm.fxml
src/org/rmj/auto/app/views/VehicleMakeFormController.java
src/org/rmj/auto/app/views/VehicleModelFormController.java
src/org/rmj/auto/app/views/VehicleTypeFormController.java

Changed retrieval of Make, Model, Type and Color after saving.

Update Vehicle Make, Model, Type and Color Controller

---

src/org/rmj/auto/app/sales/InquiryForm.fxml
src/org/rmj/auto/app/sales/InquiryFormController.java
src/org/rmj/auto/app/sales/InquiryLostSaleFormController.java
src/org/rmj/auto/app/sales/InquiryRefundPrint.fxml
src/org/rmj/auto/app/sales/InquiryRefundPrintController.java
src/org/rmj/auto/app/sales/InquiryTableRefund.java
src/org/rmj/auto/app/views/CustomerForm.fxml
src/org/rmj/auto/app/views/CustomerFormController.java
src/org/rmj/auto/app/views/CustomerTableVehicleInfo.java
src/org/rmj/auto/app/views/FXMLMenuParameterForm.java
src/org/rmj/auto/app/views/VehicleColorFormController.java
src/org/rmj/auto/app/views/VehicleDescriptionFormController.java
src/org/rmj/auto/app/views/VehicleEngineFrameFormatForm.fxml
src/org/rmj/auto/app/views/VehicleEngineFrameFormatFormController.java
src/org/rmj/auto/app/views/VehicleModelForm.fxml
src/org/rmj/auto/app/views/VehicleModelFormController.java
src/org/rmj/auto/app/views/VehicleNewOwnerForm.fxml
src/org/rmj/auto/app/views/VehicleNewOwnerFormController.java
src/org/rmj/auto/app/views/VehicleTypeFormController.java

- Replaced button under inquiry process: btnProcess, btnModify and btnApply at main button area.
- Added minor script for customer vehicle info entry.
- Added minor script for Vehicle Ingine Frame Format Entry.
- Call clientvehicleinfo class and test setting of data to class.
- Populate vehicle info table.
- Table: Commented unused arguments.
- Test class with gui: Add, Edit and Save and search for MAKE, MODEL, TYPE, TRANSMISSION, COLOR AND YEAR and Search for available vehicle.
- Added retrieval of currently saved data on btnSave.
- Added main functionality for engine frame entry.
- Added setting of make and model ID and Description when opening engine frame entry window.
- Test visibility of fields and
- Added validation for engine and frame before setting value to class.
- Added …

Bug Fixes: Update Customer Vehicle Info, Vehicle Description Parameter and Added Inquiry Refund

---

src/org/rmj/auto/app/parts/BinEntryParam.fxml
src/org/rmj/auto/app/parts/BinEntryParamController.java
src/org/rmj/auto/app/parts/BrandEntryParam.fxml
src/org/rmj/auto/app/parts/BrandEntryParamController.java
src/org/rmj/auto/app/parts/CategoryEntryParam.fxml
src/org/rmj/auto/app/parts/CategoryEntryParamController.java
src/org/rmj/auto/app/parts/InvTypeEntryParam.fxml
src/org/rmj/auto/app/parts/InvTypeEntryParamController.java
src/org/rmj/auto/app/parts/InventoryLocationParam.fxml
src/org/rmj/auto/app/parts/InventoryLocationParamController.java
src/org/rmj/auto/app/parts/MeasurementEntryParam.fxml
src/org/rmj/auto/app/parts/MeasurementEntryParamController.java
src/org/rmj/auto/app/parts/SectionEntryParam.fxml
src/org/rmj/auto/app/parts/SectionEntryParamController.java
src/org/rmj/auto/app/parts/WareHouseEntryParam.fxml
src/org/rmj/auto/app/parts/WareHouseEntryParamController.java

- Warehouse GUI & Controller
- Bin GUI & Controller
- Section GUI & Controller
- Inventory Type GUI & Controller
- Inventory Location GUI & Controller
- Brand GUI & Controller
- Category GUI & Controller
- Measurement GUI & Controller

AutoApp: Parts GUI & Controller Parameters.

---

src/org/rmj/auto/app/parts/BinEntryParamController.java
src/org/rmj/auto/app/parts/BrandEntryParamController.java
src/org/rmj/auto/app/parts/CategoryEntryParamController.java
src/org/rmj/auto/app/parts/InvTypeEntryParamController.java
src/org/rmj/auto/app/parts/InventoryLocationParamController.java
src/org/rmj/auto/app/parts/MeasurementEntryParamController.java
src/org/rmj/auto/app/parts/SectionEntryParamController.java
src/org/rmj/auto/app/parts/WareHouseEntryParamController.java

- warehouse
- section
- bin
- brand
- measurement
- inventory location
- inventory type
- category

Added additional validation to all parameters.

---

src/org/rmj/auto/app/parts/ItemEntryFormController.java
src/org/rmj/auto/app/parts/ItemEntryModel.fxml
src/org/rmj/auto/app/parts/ItemEntryModelController.java
src/org/rmj/auto/app/parts/ItemPhoto.fxml

- Changed passing argument for unload form pxeModuleName.
- Changed location for css.
- Created GUI for Model Selection.
- Fixed null exception on clicking viewbutton of photo.

Update Item Entry

---

src/org/rmj/auto/app/sales/UnitDeliveryReceiptFormController.java

Auto-App Unit Delivery Receipt Form Controller

---

src/org/rmj/auto/app/bank/BankEntryForm.fxml
src/org/rmj/auto/app/bank/BankEntryFormController.java
src/org/rmj/auto/app/parts/BinEntryParam.fxml
src/org/rmj/auto/app/parts/BrandEntryParam.fxml
src/org/rmj/auto/app/parts/CategoryEntryParam.fxml
src/org/rmj/auto/app/parts/InvTypeEntryParam.fxml
src/org/rmj/auto/app/parts/InventoryLocationParam.fxml
src/org/rmj/auto/app/parts/ItemEntryExpandModelTable.fxml
src/org/rmj/auto/app/parts/ItemEntryExpandModelTableController.java
src/org/rmj/auto/app/parts/MeasurementEntryParam.fxml
src/org/rmj/auto/app/parts/MeasurementEntryParamController.java
src/org/rmj/auto/app/parts/SectionEntryParam.fxml
src/org/rmj/auto/app/parts/WareHouseEntryParam.fxml
src/org/rmj/auto/app/sales/VehicleSalesApproval.fxml
src/org/rmj/auto/app/views/ActivityApproval.fxml
src/org/rmj/auto/app/views/ActivityForm.fxml
src/org/rmj/auto/app/views/ActivityFormController.java
src/org/rmj/auto/app/views/ActivityMemberEntryDialogController.java
src/org/rmj/auto/app/views/ActivityTownCityMainEntryDialogController.java
src/org/rmj/auto/app/views/ActivityTypeAddSource.fxml
src/org/rmj/auto/app/views/ActivityVehicleEntryDialogController.java
src/org/rmj/auto/app/views/VehicleDescriptionForm.fxml
src/org/rmj/auto/app/views/VehicleDescriptionFormController.java
src/org/rmj/auto/app/views/VehicleMakeForm.fxml
src/org/rmj/auto/app/views/VehicleModelForm.fxml
src/org/rmj/auto/app/views/VehicleNewOwnerForm.fxml

- Bank entry
- Activity Entry
- Activity Approval
- Item Parameters
- Vehicle Sales Approval
- Vehicle Description Form
- Vehicle Make Form
- Vehicle Model Form
- Vehicle New Owner Form

AutoApp enhancement and added minimal features.

---

src/org/rmj/auto/app/sales/InquiryBankApplicationForm.fxml
src/org/rmj/auto/app/sales/InquiryBankApplicationFormController.java
src/org/rmj/auto/app/sales/InquiryFollowUpForm.fxml
src/org/rmj/auto/app/sales/InquiryForm.fxml
src/org/rmj/auto/app/sales/InquiryFormController.java
src/org/rmj/auto/app/sales/InquiryLostSaleForm.fxml
src/org/rmj/auto/app/sales/InquiryRefundPrint.fxml
src/org/rmj/auto/app/sales/InquiryRefundPrintController.java
src/org/rmj/auto/app/sales/InquiryVehicleSalesAdvancesForm.fxml
src/org/rmj/auto/app/sales/InquiryVehicleSalesAdvancesFormController.java
src/org/rmj/auto/app/views/CustomerForm.fxml
src/org/rmj/auto/app/views/CustomerFormController.java
src/org/rmj/auto/app/views/VehicleColorForm.fxml
src/org/rmj/auto/app/views/VehicleEngineFrameFormatForm.fxml
src/org/rmj/auto/app/views/VehicleEngineFrameFormatFormController.java
src/org/rmj/auto/app/views/VehicleTypeForm.fxml
src/org/rmj/auto/app/views/VehicleTypeFormController.java

Inquiry Form Entry
Inquiry Follow Up
Inquiry Lost Sale
Inquiry Refund Print
Inquiry Vehicle Sales Advances
Inquiry Bank Application
Customer Form Entry
Vehicle Engine and Frame Entry
Vehicle Type 
- Added Tooltip in GUI.
- Added Feature for fields validation.
- Added Naming for label asterisks.
- Reverse set visibility for label04 and label05.
- Added condition for required field validation.
- Added visibility condition for label * of Vehicle Type Make.
- Added name for label * of Vehicle Type Make.

Autoapp Tooltip and Required Fields Feature

---

src/org/rmj/auto/app/cashiering/InvoiceForm.fxml
src/org/rmj/auto/app/cashiering/InvoiceFormController.java
src/org/rmj/auto/app/views/FXMLDocument.fxml
src/org/rmj/auto/app/views/FXMLDocumentController.java

Added Menu and Open event for Invoices:
- Acknowledgement Receipt
- Billing Statement
- Collection Receipt
- Official Receipt
- Parts Sales Invoice

Autoapp Cashiering Invoice Open Event

---

src/org/rmj/auto/app/views/CustomerForm.fxml
src/org/rmj/auto/app/views/CustomerFormController.java

- Added Toggle Group for radio buttons.
- Commented unused script for radio buttons.

Added toggle group for radio buttons

---

src/org/rmj/auto/app/sales/UnitDeliveryReceiptFormController.java
src/org/rmj/auto/app/views/DateCellDisabler.java

-Added new class datecelldisabler-for disabling date based on a parameter
-moved disabledate from unitdeliveryreceiptformcontroller to its own class

Datecelldisabler09042023

---

src/org/rmj/auto/app/sales/InquiryFormController.java
src/org/rmj/auto/app/views/VehicleColorForm.fxml

- Fixed a bug in updating inquiry payment mode and customer group.
- Added asterisk on vehicle color: color label.

Autoapp Inquiry Controller: Fixed Bug

---

src/org/rmj/auto/app/views/CustomerForm.fxml
src/org/rmj/auto/app/views/CustomerFormController.java

- Fixed enabling of fields on customer vehicle info after clicking manual button then browse button.
- Widen title combo box

Update Customer Vehicle Info

---

src/org/rmj/auto/app/sales/InquiryBankApplicationForm.fxml
src/org/rmj/auto/app/sales/InquiryBankApplicationFormController.java
src/org/rmj/auto/app/sales/InquiryForm.fxml
src/org/rmj/auto/app/sales/InquiryFormController.java
src/org/rmj/auto/app/views/FXMLDocument.fxml
src/org/rmj/auto/app/views/FXMLDocumentController.java
src/org/rmj/auto/app/views/VehicleDescriptionFormController.java

9/11/2023	Added New selection for payment mode in Inquiry Process and widen combobox for payment mode.
9/11/2023	Added New selection for payment mode in Inquiry Bank Application and widen combobox for payment mode.
9/11/2023	Replace clearfield() above OpenRecord.
9/11/2023	Changed Font of Main Menu and Label into arial
9/12/2023	Added search for branch code and loading of sales executive.

Autoapp  sales  update  additional  process

---

src/org/rmj/auto/app/sales/VSPForm.fxml
src/org/rmj/auto/app/sales/VSPFormController.java
src/org/rmj/auto/app/views/FXMLDocument.fxml
src/org/rmj/auto/app/views/FXMLDocumentController.java

- Created VSP Form UI
- Added minor script for VSP Controller
- Added open event for VSP Form

Autoapp Sales Vehicle Sales Proposal 

---

src/org/rmj/auto/app/sales/InquiryFormController.java
src/org/rmj/auto/app/views/CustomerFormController.java

- 9/21/2023	Added format on display of VSA amount in Inquiry.
- 9/25/2023	"Update newTab set style to newTab.setStyle(""-fx-font-weight: bold; -fx-pref-width: 180; -fx-font-size: 10.5px; -fx-font-family: arial;""); for opening of new tab for vehicle description."
- 9/25/2023	"Update newTab set style to newTab.setStyle(""-fx-font-weight: bold; -fx-pref-width: 180; -fx-font-size: 10.5px; -fx-font-family: arial;""); for opening of new tab for vehicle sales proposal."

Update Customer and Inquiry Controller

---

src/org/rmj/auto/app/cashiering/VehicleSalesInvoiceForm.fxml
src/org/rmj/auto/app/cashiering/VehicleSalesInvoiceFormController.java
src/org/rmj/auto/app/sales/InquiryFormController.java
src/org/rmj/auto/app/views/FXMLDocument.fxml
src/org/rmj/auto/app/views/FXMLDocumentController.java

9/25/2023	Created UI for vehicle sales invoice.
9/25/2023	Set grider on controller.
9/29/2023	Added Functionality for Vehicle Sales Invoice Controller.
9/30/2023	Added Validation on input discount amount.
9/30/2023	Disable un used script.
9/30/2023	set Total and Customer Name font weight to bold.
10/3/2023	Added combobox for customer type.
10/4/2023	Added functionality for text field search.
10/5/2023	Added functionality for cancel vehicle sales invoice.

Autoapp Sales : Vehicle Sales Invoice UI and Controller

---

src/org/rmj/auto/app/sales/InquiryFollowUpFormController.java
src/org/rmj/auto/app/sales/InquiryForm.fxml
src/org/rmj/auto/app/sales/InquiryFormController.java
src/org/rmj/auto/app/sales/InquiryLostSaleForm.fxml
src/org/rmj/auto/app/sales/InquiryLostSaleFormController.java
src/org/rmj/auto/app/views/CustomerFormController.java

10/16/2023 Added setisFollowUp on saving.
9/30/2023 Added auto select Customer Inquiry Tab when clicking Add and getSelectedItem.
10/9/2023 Added clear fields for inquiry type.
10/14/2023 Call open event for vehicle sales proposal for inquiry convertion to vsp.
10/14/2023 Added script for cancellation of VSP: added calling of VehicleSalesProposalMaster Class and call cancelVSP.
10/14/2023 Added validation for enabling and disabling of fields based on selected tag.
- Fixed error on adding customer address.
- Refactor script for contact information.
- Added label on top for Inquiry Status

Autoapp Sales VSP cancel and Inquiry lost sale 

---

src/org/rmj/auto/app/views/CustomerAddressForm.fxml
src/org/rmj/auto/app/views/CustomerAddressFormController.java
src/org/rmj/auto/app/views/CustomerContactForm.fxml
src/org/rmj/auto/app/views/CustomerContactFormController.java
src/org/rmj/auto/app/views/CustomerEmailForm.fxml
src/org/rmj/auto/app/views/CustomerEmailFormController.java
src/org/rmj/auto/app/views/CustomerForm.fxml
src/org/rmj/auto/app/views/CustomerFormController.java
src/org/rmj/auto/app/views/CustomerSocialMediaForm.fxml
src/org/rmj/auto/app/views/CustomerSocialMediaFormController.java
src/org/rmj/auto/app/views/CustomerTableAddress.java
src/org/rmj/auto/app/views/CustomerTableEmail.java
src/org/rmj/auto/app/views/CustomerTableMobile.java
src/org/rmj/auto/app/views/CustomerTableSocialMedia.java

10/23/2023	Created UI and Functionality for Customer Address.
10/23/2023	Created UI and Functionality for Customer Mobile.
10/23/2023	Created UI and Functionality for Customer Email.
10/23/2023	Created UI and Functionality for Customer Social Media.
10/23/2023	Commented script for Customer Contact information.
10/24/2023	Added script on table clicked of customer contact information.

Autoapp Customer Contact Update New Process

---

src/org/rmj/auto/app/views/FXMLDocument.fxml

10/25/2023	Move parameters into main menu.
#87

Autoapp Parameters Menu

---

src/org/rmj/auto/app/sales/ReservationPrint.fxml
src/org/rmj/auto/app/sales/ReservationPrintController.java

- refactored reservation print GUI, added print button

Auto-App Refactor Reservation Print

---

src/org/rmj/auto/app/sales/VehicleSalesApproval.fxml
src/org/rmj/auto/app/sales/VehicleSalesApprovalController.java

Rearrange table column disabled.

Auto-App Vehicle Sales Approval Refactor Table

---

src/org/rmj/auto/app/views/ActivityApproval.fxml
src/org/rmj/auto/app/views/ActivityApprovalController.java
src/org/rmj/auto/app/views/ActivityForm.fxml
src/org/rmj/auto/app/views/ActivityFormController.java
src/org/rmj/auto/app/views/ActivityMemberEntryDialog.fxml
src/org/rmj/auto/app/views/ActivityMemberEntryDialogController.java
src/org/rmj/auto/app/views/ActivityTownCityMainEntryDialog.fxml
src/org/rmj/auto/app/views/ActivityTownCityMainEntryDialogController.java
src/org/rmj/auto/app/views/ActivityVehicleDialog.fxml
src/org/rmj/auto/app/views/ActivityVehicleDialogController.java

Re-arrange table column disabled.
- Town Dialog table
- Member Dialog table
- Vehicle Dialog table
- Budget Table
- Task Table
- Activity Approval Table

 Auto-App Activity Entry Form Refactor Table

---

src/org/rmj/auto/app/sales/InquiryForm.fxml
src/org/rmj/auto/app/sales/InquiryFormController.java
src/org/rmj/auto/app/sales/InquiryVehicleSalesAdvancesFormController.java
src/org/rmj/auto/app/views/CustomerAddressFormController.java
src/org/rmj/auto/app/views/CustomerContactFormController.java
src/org/rmj/auto/app/views/CustomerForm.fxml
src/org/rmj/auto/app/views/CustomerFormController.java
src/org/rmj/auto/app/views/CustomerTableVehicleInfo.java
src/org/rmj/auto/app/views/CustomerVehicleInfoForm.fxml
src/org/rmj/auto/app/views/CustomerVehicleInfoFormController.java
src/org/rmj/auto/app/views/FXMLDocument.fxml
src/org/rmj/auto/app/views/FXMLDocumentController.java
src/org/rmj/auto/app/views/InputTextFormatter.java

- Added validation for payment mode
- Refactor Vehicle Sales Advances
- Removed search F3 in inquiry search
- Refactor Customer Information, address and mobile
- Removed customer vehicle information entry created new utility for it.
- Created new utility for Customer and sales Vehicle Information Entry.
- Added menu for Vehicle Sales Information
- Changed menu description from entry to information.
- Refactor Input text formatter

Autoapp  Created utility for Customer and Sales Vehicle Information, Refactor Customer Information, Inquiry, Main Menu

---

src/org/rmj/auto/app/sales/UnitDeliveryReceiptForm.fxml
src/org/rmj/auto/app/sales/UnitDeliveryReceiptFormController.java
src/org/rmj/auto/app/sales/VSPFormController.java
src/org/rmj/auto/app/sales/VSPFormPrintController.java

- added validation in VSP buyer and co-buyer
- added std fleet and stl fleet vsp print
- changes in unit delivery receipt

Refactor VSP & Unit Delivery Receipt Controller and GUI

---

src/org/rmj/auto/app/sales/VSPPartsRequest.fxml
src/org/rmj/auto/app/sales/VSPPartsRequestController.java
src/org/rmj/auto/app/views/CustomerVehicleInfoFormController.java

- Created New UI for Sales Parts Request to be continued by Dave.
- fixed invalid date format of dr date at customer vehicle information.

Autoapp Sales : Created New UI for Sales Parts Request and fixed invalid date format of dr date at customer vehicle info

---

src/org/rmj/auto/app/sales/VSPFormController.java
src/org/rmj/auto/app/sales/VSPFormPrintController.java
src/org/rmj/auto/app/sales/VSPPartsDialog.fxml
src/org/rmj/auto/app/sales/VSPPartsDialogController.java
src/org/rmj/auto/app/sales/VSPPartsRequest.fxml
src/org/rmj/auto/app/sales/VSPPartsRequestController.java
src/org/rmj/auto/app/sales/VSPPendingPartsRequest.fxml
src/org/rmj/auto/app/sales/VSPPendingPartsRequestController.java
src/org/rmj/auto/app/sales/VSPTableMasterList.java
src/org/rmj/auto/app/sales/VSPTablePartList.java
src/org/rmj/auto/app/sales/VehicleSalesApprovalTable.java
src/org/rmj/auto/app/service/JobOrderFormController.java
src/org/rmj/auto/app/service/PartsInformationController.java
src/org/rmj/auto/app/views/FXMLDocument.fxml
src/org/rmj/auto/app/views/FXMLDocumentController.java

- VSP Pending Part Request GUI & CONTROLLER
- VSP Parts Request GUI & CONTROLLER

Auto-App VSP Part Request 

---

src/org/rmj/auto/app/cashiering/VehicleSalesInvoiceForm.fxml
src/org/rmj/auto/app/views/CustomerContactFormController.java
src/org/rmj/auto/app/views/CustomerVehicleInfoFormController.java

VehicleSalesInvoiceForm - Update VSI Form fxml
CustomerContactFormController - Update textlimiter from 12 to 11
CustomerVehicleInfoFormController - Added Message box for Okay/Cancel on
btnCancel.

Autoapp 01-05-2024 Controller update

---

src/org/rmj/auto/app/cashiering/VehicleSalesInvoicePrintController.java
src/org/rmj/auto/app/sales/InquiryFormController.java
src/org/rmj/auto/app/sales/SalesAgentForm.fxml
src/org/rmj/auto/app/sales/SalesAgentFormController.java
src/org/rmj/auto/app/sales/SalesAgentTableList.java
src/org/rmj/auto/app/sales/UnitDeliveryReceiptPrintController.java
src/org/rmj/auto/app/views/CancelForm.fxml
src/org/rmj/auto/app/views/CancelFormController.java
src/org/rmj/auto/app/views/FXMLDocument.fxml
src/org/rmj/auto/app/views/FXMLDocumentController.java

- 1/18/2024 Re design UI for adding Agent and Sales Executive.
- 1/19/2024 Added script for adding sales agent and executive.
- 1/23/2024 Added deactivation remarks and approve and disapprove.
- Created Table for list and transactions
- Added menu for sales executive
- Added deactivate word
- 1/22/2024 Refactor selection of sales agent and executive.
- Added updating of cPrintedx

Autoapp Sales Agent and Executive Information : Refactor Inquiry, UDR and VSI

---

src/org/rmj/auto/app/bank/BankEntryForm.fxml
src/org/rmj/auto/app/bank/BankEntryFormController.java
src/org/rmj/auto/app/insurance/InsuranceInformation.fxml
src/org/rmj/auto/app/insurance/InsuranceInformationController.java
src/org/rmj/auto/app/insurance/InsuranceTableList.java
src/org/rmj/auto/app/views/FXMLDocument.fxml
src/org/rmj/auto/app/views/FXMLDocumentController.java

- Insurance Information Entry GUI & Controller (NEW)
- Added Insurance Menu
- Remove branch abbrev in Bank Information GUI & Controller

Auto-App Added Insurance Information & Refactor Bank

---

src/org/rmj/auto/app/sales/SalesAgentFormController.java
src/org/rmj/auto/app/views/FXMLDocument.fxml
src/org/rmj/auto/app/views/FXMLDocumentController.java

Update FXML Document
Sales Agent

Update FXML Document

---

src/org/rmj/auto/app/cashiering/VehicleSalesInvoiceFormController.java
src/org/rmj/auto/app/sales/InquiryFormController.java
src/org/rmj/auto/app/sales/SalesAgentFormController.java
src/org/rmj/auto/app/views/CustomerAddressFormController.java
src/org/rmj/auto/app/views/CustomerContactFormController.java
src/org/rmj/auto/app/views/CustomerEmailFormController.java
src/org/rmj/auto/app/views/CustomerFormController.java

- Added validation on clearing data at combobox.setOnAction
- Call initListTable() on initialization
- Added validation : User cannot set primary that is inactive.

Autoapp 01 05 2024  Controller Update

---

src/org/rmj/auto/app/views/CustomerAddressForm.fxml
src/org/rmj/auto/app/views/CustomerAddressFormController.java
src/org/rmj/auto/app/views/CustomerContactFormController.java
src/org/rmj/auto/app/views/CustomerEmailFormController.java
src/org/rmj/auto/app/views/CustomerFormController.java
src/org/rmj/auto/app/views/CustomerSocialMediaFormController.java
src/org/rmj/auto/app/views/CustomerVehicleInfoFormController.java

- Removed unused script and moved calling of Address, Mobile, Email, Social Media and Client Vehicle Info Classes to ClientMaster Class.

Autoapp 01-29-2024 : Refactor Client Information Controllers

---

src/org/rmj/auto/app/views/FXMLDocumentController.java

Adding new feature right click mouse (Close Tab, Close Other Tabs, Close all Tabs)

---

src/org/rmj/auto/app/sales/InquiryBankApplicationFormController.java
src/org/rmj/auto/app/sales/InquiryFormController.java
src/org/rmj/auto/app/sales/SalesAgentFormController.java
src/org/rmj/auto/app/sales/UnitDeliveryReceiptFormController.java
src/org/rmj/auto/app/sales/VSPFormController.java
src/org/rmj/auto/app/service/JobOrderFormController.java
src/org/rmj/auto/app/views/CustomerAddressForm.fxml
src/org/rmj/auto/app/views/CustomerAddressFormController.java
src/org/rmj/auto/app/views/CustomerFormController.java
src/org/rmj/auto/app/views/CustomerVehicleInfoFormController.java
src/org/rmj/auto/app/views/FXMLDocument.fxml
src/org/rmj/auto/app/views/FXMLDocumentController.java

- Changed title for sales agent into referral agent.
- Added Open Record after saving
- Changed sales job order information into Sales Job Order.
- Added saving into json when user open job order at vsp jo button.
- Added saving into json when user open job order at vsp jo button.
- Changed sales agent into referral agent.
- Update saving on json at logout function.
- Added OpenRecord after saving data.
- Added Message box after cancellation.

Autoapp 01 30 2024  Controller Update

---

src/org/rmj/auto/app/parts/ItemEntryFormController.java
src/org/rmj/auto/app/sales/InquiryForm.fxml
src/org/rmj/auto/app/sales/InquiryFormController.java
src/org/rmj/auto/app/views/CustomerAddressFormController.java
src/org/rmj/auto/app/views/CustomerForm.fxml
src/org/rmj/auto/app/views/CustomerFormController.java
src/org/rmj/auto/app/views/FXMLDocumentController.java

- added validation for customer addresses.
- added optional contact person to the inquiry form.

Auto App Customer & Inquiry Form (Refactor)

---

src/org/rmj/auto/app/sales/InquiryFormController.java
src/org/rmj/auto/app/views/CustomerFormController.java

- Added clearing of sales executive master.
- Added saveState in btnTabRem and btnTabAdd action.

Update Inquiry Form Controller, Customer Controller

---

src/org/rmj/auto/app/sales/InquiryFormController.java
src/org/rmj/auto/app/sales/VSPFormController.java
src/org/rmj/auto/app/service/JobOrderFormController.java
src/org/rmj/auto/app/views/FXMLDocumentController.java

- Refactor Context Menu, now user can't close other tabs when the only tab is 1.
- VSP Controller (added few validation for disable new job order button & refactor context menu)
- Inquiry Controller (refactor context menu)
author: rsie & dave

Autoa App VSP, INQUIRY AND TAB/CONTEXT MENU REFACTOR

---

src/org/rmj/auto/app/views/ActivityTypeAddSource.fxml
src/org/rmj/auto/app/views/CustomerVehicleInfoFormController.java
src/org/rmj/auto/app/views/VehicleNewOwnerForm.fxml
src/org/rmj/auto/app/views/VehicleNewOwnerFormController.java

Update Customer Vehicle Info and New Owner
- Added validation and loading of previous owner.
Update Activity Type Add Source
- Call css configuration in AnchorPane

Autoapp 02-24-2024 - Vehicle Ownership Transfer
